env:
  TERM: xterm-256color

#  shell:
#  program: /bin/zsh
#  args:
#  - -l
#  - -c
#  - "tmux"

window:
  dimensions:
    columns: 100
    lines: 30
  padding:
    x: 3
    y: 3
  position:
    x: 130
    y: 70
  decorations: none
  dynamic_title: true
  opacity: 0.7

class:
  gtk_theme_variant: Dracula 

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Normal
  bold:
    family: mononoki Nerd Font
    style: Bold
  italic:
    family: VictorMono Nerd Font
    style: Italic
  size: 20
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0


draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: "#1a1a2e"
    foreground: "#e2d5bc"

  normal:
    black: "#bbbbbb"
    red: "#fb5c8e"
    green: "#84c49b"
    yellow: "#f6e08b"
    blue: "#f47d49"
    magenta: "#a29dff"
    cyan: "#93c5e6"
    white: "#f2f2f2"

  bright:
    black: "#bbbbbb"
    red: "#dd5289"
    green: "#9fd3b3"
    yellow: "#fff0b8"
    blue: "#f79f79"
    magenta: "#b2aeff"
    cyan: "#aed9f6"
    white: "#f2f2f2"

  dim:
    black: "#444444"
    red: "#e68ac1"
    green: "#cae7b9"
    yellow: "#fee074"
    blue: "#f79f79"
    magenta: "#565393"
    cyan: "#c4d1f5"
    white: "#f2f2f2"

selection:
  text: "0xffffff"
  background: "0xF34F4D"
  white: "0xffffff"
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

alt_send_esc: true


